#!/usr/bin/env bash

set -e

source dev-container-features-test-lib

echo "*********** az version ***********"
# az version || echo "mask error"
echo "**********************************"

check "cache dir permission" bash -c "test -w /dc/azure"
check "check symlink" bash -c 'test $(readlink "$HOME/.azure") == "/dc/azure/"'

az extension list

matching_extension_count=$(az extension list --output tsv --query "length([?name == 'containerapp' || name == 'ssh' ])")
check "check cliextensions" bash -c "test $matching_extension_count -eq 2"

reportResults

# Helpful commands for testing
# devcontainer features test --features azure-cli-persistence --filter with_exten --skip-autogenerated --skip-duplicated
# devcontainer features test --features azure-cli-persistence --filter with_exten --skip-autogenerated --skip-duplicated --preserve-test-containers ## allows docker exec for inspection