name: "CI - Test Features"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # continue-on-error: true
    strategy:
      matrix:
        include:
          - features: "dev-tunnel"
            baseImage: "mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18"
            remoteUser: node
          - features: "dev-tunnel"
            baseImage: "mcr.microsoft.com/devcontainers/base:ubuntu"
            remoteUser: root
          - features: shell-history
            baseImage: mcr.microsoft.com/devcontainers/base:ubuntu
            remoteUser: vscode
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.feature }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --features ${{ matrix.feature }} --base-image ${{ matrix.baseImage }} --remote-user ${{ matrix.remoteUser }} .


  # test-global:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: "Install latest devcontainer CLI"
  #       run: npm install -g @devcontainers/cli

  #     - name: "Testing global scenarios"
  #       run: devcontainer features test --global-scenarios-only .
